# Generated by Django 5.2.8 on 2025-11-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_familiar_fam",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Código Familiar"
                    ),
                ),
                ("dat_atual_fam", models.DateField(verbose_name="Data de Atualização")),
                (
                    "vlr_renda_media_fam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Renda Média Familiar",
                    ),
                ),
                (
                    "vlr_renda_total_fam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Renda Total Familiar",
                    ),
                ),
                (
                    "marc_pbf",
                    models.BooleanField(
                        default=False, verbose_name="Beneficiário Bolsa Família"
                    ),
                ),
                (
                    "qtde_pessoas",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de Pessoas"
                    ),
                ),
                (
                    "nom_logradouro_fam",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Logradouro"
                    ),
                ),
                (
                    "num_logradouro_fam",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "nom_localidade_fam",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bairro/Localidade"
                    ),
                ),
                (
                    "num_cep_logradouro_fam",
                    models.CharField(blank=True, max_length=8, verbose_name="CEP"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Família",
                "verbose_name_plural": "Famílias",
                "ordering": ["-dat_atual_fam"],
            },
        ),
        migrations.CreateModel(
            name="Beneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_beneficio",
                    models.CharField(max_length=100, verbose_name="Tipo de Benefício"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "data_referencia",
                    models.DateField(verbose_name="Data de Referência"),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="cecad.familia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício",
                "verbose_name_plural": "Benefícios",
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_nis_pessoa_atual",
                    models.CharField(max_length=11, unique=True, verbose_name="NIS"),
                ),
                ("nom_pessoa", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "num_cpf_pessoa",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "dat_nasc_pessoa",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "cod_parentesco_rf_pessoa",
                    models.IntegerField(
                        choices=[
                            (1, "Responsável Familiar"),
                            (2, "Cônjuge ou Companheiro"),
                            (3, "Filho(a)"),
                            (4, "Enteado(a)"),
                            (5, "Neto(a) ou Bisneto(a)"),
                            (6, "Pai ou Mãe"),
                            (7, "Sogro(a)"),
                            (8, "Irmão ou Irmã"),
                            (9, "Genro ou Nora"),
                            (10, "Outros Parentes"),
                            (11, "Não Parente"),
                        ],
                        default=1,
                        verbose_name="Código Parentesco",
                    ),
                ),
                (
                    "cod_curso_frequentou_pessoa_membro",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Curso Frequentado"
                    ),
                ),
                (
                    "cod_ano_serie_frequentou_pessoa_membro",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano/Série Frequentado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="cecad.familia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
            },
        ),
    ]
