# Generated by Django 5.2.8 on 2025-11-19 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Importação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("error", "Erro"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="imports/cecad/",
                        verbose_name="Arquivo Original",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Importação",
                "verbose_name_plural": "Lotes de Importação",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.AlterField(
            model_name="familia",
            name="cod_familiar_fam",
            field=models.CharField(max_length=11, verbose_name="Código Familiar"),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="num_cpf_pessoa",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="num_nis_pessoa_atual",
            field=models.CharField(max_length=11, verbose_name="NIS"),
        ),
        migrations.AddField(
            model_name="beneficio",
            name="import_batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficios",
                to="cecad.importbatch",
                verbose_name="Lote de Importação",
            ),
        ),
        migrations.AddField(
            model_name="familia",
            name="import_batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="familias",
                to="cecad.importbatch",
                verbose_name="Lote de Importação",
            ),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="import_batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pessoas",
                to="cecad.importbatch",
                verbose_name="Lote de Importação",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familia",
            unique_together={("cod_familiar_fam", "import_batch")},
        ),
        migrations.AlterUniqueTogether(
            name="pessoa",
            unique_together={("num_nis_pessoa_atual", "import_batch")},
        ),
    ]
