# Generated by Django 5.2.8 on 2025-11-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0002_importbatch_alter_familia_cod_familiar_fam_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficio",
            name="import_batch",
        ),
        migrations.AlterUniqueTogether(
            name="pessoa",
            unique_together={("num_nis_pessoa_atual", "familia")},
        ),
        migrations.RemoveField(
            model_name="pessoa",
            name="import_batch",
        ),
    ]
