# Generated by Django 5.2.8 on 2025-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0003_remove_beneficio_import_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Mensagem de Erro"),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="processed_rows",
            field=models.IntegerField(default=0, verbose_name="Linhas Processadas"),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="total_rows",
            field=models.IntegerField(default=0, verbose_name="Total de Linhas"),
        ),
    ]
