# Generated by Django 5.2.8 on 2025-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecad', '0004_importbatch_error_message_importbatch_processed_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cod_sexo_pessoa',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino')], default='2', max_length=1, verbose_name='Sexo'),
        ),
    ]
