# Generated by Django 5.2.8 on 2025-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0005_pessoa_cod_sexo_pessoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="familia",
            name="ref_cad",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Referência Cadastro Único",
            ),
        ),
        migrations.AddField(
            model_name="familia",
            name="ref_pbf",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Referência Bolsa Família",
            ),
        ),
    ]
