# Generated by Django 5.2.8 on 2025-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0006_familia_ref_cad_familia_ref_pbf"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="batch_type",
            field=models.CharField(
                choices=[("full", "Importação Completa"), ("correction", "Correção")],
                default="full",
                max_length=20,
                verbose_name="Tipo de Lote",
            ),
        ),
    ]
