# Generated by Django 5.2.8 on 2025-12-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0007_importbatch_batch_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="familia",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="familia",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="familias",
                to="cecad.importbatch",
                verbose_name="Lote de Importação",
            ),
        ),
        migrations.AddConstraint(
            model_name="familia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("import_batch__isnull", False)),
                fields=("cod_familiar_fam", "import_batch"),
                name="unique_familia_per_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="familia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("import_batch__isnull", True)),
                fields=("cod_familiar_fam",),
                name="unique_manual_familia",
            ),
        ),
    ]
