# Generated by Django 5.2.8 on 2025-11-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cecad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Ex: renda_per_capita, vacinacao_em_dia",
                        unique=True,
                        verbose_name="Código Identificador",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("pontos", models.IntegerField(default=10, verbose_name="Pontos")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=4, verbose_name="Peso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério",
                "verbose_name_plural": "Critérios",
            },
        ),
        migrations.CreateModel(
            name="Validacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                            ("em_analise", "Em Análise"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "pontuacao_total",
                    models.IntegerField(default=0, verbose_name="Pontuação Total"),
                ),
                (
                    "data_validacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Validação"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacoes",
                        to="cecad.familia",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validação",
                "verbose_name_plural": "Validações",
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=100, verbose_name="Tipo de Documento"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "validado",
                    models.BooleanField(default=False, verbose_name="Validado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.validacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.CreateModel(
            name="ValidacaoCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atendido",
                    models.BooleanField(default=False, verbose_name="Atendido"),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observação"
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.criterio"
                    ),
                ),
                (
                    "validacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios_avaliados",
                        to="core.validacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Critério",
                "verbose_name_plural": "Avaliações de Critérios",
                "unique_together": {("validacao", "criterio")},
            },
        ),
    ]
