# Generated by Django 5.2.8 on 2025-11-20 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validacao",
            name="em_avaliacao_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário que está avaliando atualmente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validacoes_em_avaliacao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validacao",
            name="iniciado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o usuário iniciou a avaliação",
                null=True,
                verbose_name="Iniciado em",
            ),
        ),
        migrations.AlterField(
            model_name="validacao",
            name="operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validacoes_finalizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
