# Generated by Django 5.2.8 on 2025-11-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cecad", "0003_remove_beneficio_import_batch_and_more"),
        ("core", "0002_add_lock_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("desenvolvimento_social", "Desenvolvimento Social"),
                            ("saude", "Saúde"),
                            ("educacao", "Educação"),
                            ("documentacao", "Documentação"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "ordem",
                    models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Ex: users, heart, academic-cap, document-text",
                        max_length=50,
                        verbose_name="Ícone (nome Heroicon)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["ordem"],
            },
        ),
        migrations.AlterModelOptions(
            name="criterio",
            options={
                "ordering": ["categoria__ordem", "codigo"],
                "verbose_name": "Critério",
                "verbose_name_plural": "Critérios",
            },
        ),
        migrations.AddField(
            model_name="criterio",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="criterios",
                to="core.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoPessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rg", "RG"),
                            ("cpf", "CPF"),
                            ("certidao_nascimento", "Certidão de Nascimento"),
                            ("certidao_casamento", "Certidão de Casamento"),
                            ("carteira_vacinacao", "Carteira de Vacinação"),
                            ("comprovante_matricula", "Comprovante de Matrícula"),
                            ("historico_escolar", "Histórico Escolar"),
                            ("declaracao_escolar", "Declaração Escolar"),
                            ("exame_citopatologico", "Exame Citopatológico"),
                            ("comprovante_residencia", "Comprovante de Residência"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos/pessoas/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número do Documento"
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "validado",
                    models.BooleanField(default=False, verbose_name="Validado"),
                ),
                (
                    "validado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Validado em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="cecad.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_validados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Pessoal",
                "verbose_name_plural": "Documentos Pessoais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="validacaocriterio",
            name="documento_comprobatorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criterios_comprovados",
                to="core.documentopessoa",
                verbose_name="Documento Comprobatório",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoValidacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=100, verbose_name="Tipo de Documento"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos/validacoes/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_anexos",
                        to="core.validacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Validação",
                "verbose_name_plural": "Documentos das Validações",
            },
        ),
        migrations.DeleteModel(
            name="Documento",
        ),
    ]
