# Generated by Django 5.2.8 on 2025-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoria_alter_criterio_options_criterio_categoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pontuacao_minima_aprovacao",
                    models.IntegerField(
                        default=50,
                        help_text="Pontuação mínima necessária para que uma validação seja aprovada.",
                        verbose_name="Pontuação Mínima para Aprovação",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
    ]
