# Generated by Django 5.2.8 on 2025-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_configuracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracao",
            name="quantidade_vagas",
            field=models.IntegerField(
                default=1000,
                help_text="Número total de vagas disponíveis para o benefício.",
                verbose_name="Quantidade de Vagas",
            ),
        ),
    ]
