# Generated by Django 5.2.8 on 2025-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracao_quantidade_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='aplica_se_a_rf_homem',
            field=models.BooleanField(default=True, help_text='Se desmarcado, este critério será ignorado se o Responsável Familiar for homem.', verbose_name='Aplica-se a RF homem?'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='aplica_se_a_sem_criancas',
            field=models.BooleanField(default=True, help_text='Se desmarcado, este critério será ignorado para famílias que não possuem crianças (menores de 18 anos).', verbose_name='Aplica-se a famílias sem crianças?'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='aplica_se_a_unipessoais',
            field=models.BooleanField(default=True, help_text='Se desmarcado, este critério será ignorado para famílias de uma única pessoa.', verbose_name='Aplica-se a famílias unipessoais?'),
        ),
    ]
