# Generated by Django 5.2.8 on 2025-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_criterio_aplica_se_a_rf_homem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='idade_maxima',
            field=models.IntegerField(blank=True, help_text='Critério só se aplica se houver membro com idade igual ou inferior a esta.', null=True, verbose_name='Idade Máxima do Membro'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='idade_minima',
            field=models.IntegerField(blank=True, help_text='Critério só se aplica se houver membro com idade igual ou superior a esta.', null=True, verbose_name='Idade Mínima do Membro'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='sexo_necessario',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Feminino')], help_text='Critério só se aplica se houver membro deste sexo (respeitando a faixa etária, se definida).', max_length=1, null=True, verbose_name='Sexo Necessário'),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='aplica_se_a_unipessoais',
            field=models.BooleanField(default=True, help_text='Se desmarcado, este critério NÃO será exigido para famílias de uma única pessoa.', verbose_name='Aplica-se a famílias unipessoais?'),
        ),
    ]
