# Generated by Django 5.2.8 on 2025-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_criterio_idade_maxima_criterio_idade_minima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validacaocriterio",
            name="aplicavel",
            field=models.BooleanField(default=True, verbose_name="Aplicável"),
        ),
    ]
