# Generated by Django 5.2.8 on 2025-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_validacaocriterio_aplicavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='parentescos_permitidos',
            field=models.CharField(blank=True, help_text='Códigos de parentesco permitidos (separados por vírgula). Ex: 1,2 para RF e Cônjuge.', max_length=50, verbose_name='Parentescos Permitidos'),
        ),
    ]
