# Generated by Django 5.2.8 on 2025-11-26 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_criterio_parentescos_permitidos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidacaoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "editado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Editado em"),
                ),
                (
                    "campos_alterados",
                    models.JSONField(
                        help_text="Dicionário com campos modificados e seus valores antes/depois",
                        verbose_name="Campos Alterados",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Status Anterior"
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Status Novo"
                    ),
                ),
                (
                    "pontuacao_anterior",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Pontuação Anterior"
                    ),
                ),
                (
                    "pontuacao_nova",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Pontuação Nova"
                    ),
                ),
                (
                    "observacao_edicao",
                    models.TextField(
                        blank=True,
                        help_text="Justificativa opcional para a edição",
                        verbose_name="Motivo da Edição",
                    ),
                ),
                (
                    "editado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edicoes_validacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editado por",
                    ),
                ),
                (
                    "validacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_edicoes",
                        to="core.validacao",
                        verbose_name="Validação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Edição",
                "verbose_name_plural": "Histórico de Edições",
                "ordering": ["-editado_em"],
            },
        ),
    ]
