# Generated by Django 5.2.8 on 2025-12-02 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cecad", "0009_pessoatransferhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BSDIExportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exports/bsdi/%Y/%m/",
                        verbose_name="Arquivo XLS",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="processando",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_beneficiarios",
                    models.IntegerField(
                        default=0,
                        help_text="Quantidade de famílias aprovadas incluídas na lista",
                        verbose_name="Total de Beneficiários",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "gerado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exportacoes_bsdi",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerado por",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        help_text="Lote CECAD do qual os beneficiários aprovados foram extraídos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exportacoes_bsdi",
                        to="cecad.importbatch",
                        verbose_name="Lote de Importação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação BSDI",
                "verbose_name_plural": "Exportações BSDI",
                "ordering": ["-criado_em"],
            },
        ),
    ]
